backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: 'src/lib/images' # Media files will be stored in the repo under static/uploads
public_folder: '../images' # The src attribute for uploaded media will begin with /uploads

collections:
  - name: 'categories' # Used in routes, e.g., /admin/collections/blog
    label: 'Categories' # Used in the UI
    folder: 'src/categories/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Order', name: 'order', widget: 'number' }

      - label: 'Image'
        name: 'image'
        widget: 'object'
        collapsed: false
        fields: 
          - {lable: "Source", name: "source", widget: "image"}
          - {label: "Alt", name: "alt", widget: "string"}

      - label: 'Products'
        name: 'products'
        widget: 'relation'
        collection: 'products'
        value_field: 'title'
        search_fields: ['title']
        multiple: true
  
      - { label: 'Description', name: 'description', widget: 'markdown' }
        
      - label: 'Description Images'
        name: 'description_images'
        widget: 'object'
        collapsed: true
        fields: 
          - label: 'Image 1'
            name: "image_1"
            widget: "object"
            colapsed: false
            fields:
              - { label: "Image 1 Source", name: "image_1_source", widget: "image" }
              - { label: "Image 1 Alt", name: "image_1_alt", widget: "string" }
                
          - label: 'Image 2'
            name: "image_2"
            widget: "object"
            colapsed: false
            fields:
              - { label: "Image 2 Source", name: "image_2_source", widget: "image" }
              - { label: "Image 2 Alt", name: "image_2_alt", widget: "string" }
                
          - label: 'Image 3'
            name: "image_3"
            widget: "object"
            colapsed: false
            fields:
              - { label: "Image 3 Source", name: "image_3_source", widget: "image" }
              - { label: "Image 3 Alt", name: "image_3_alt", widget: "string" }
                
      - { label: 'Info', name: 'info', widget: 'markdown' }
        
      - label: 'Info Images'
        name: 'info_images'
        widget: 'list'
        field: { label: 'Image', name: image, widget: image }

      - label: "SEO"
        name: "seo"
        widget: "object"
        colapsed: false
        fields: 
          - {label: "SEO Title", name: "seo_title", widget: "string"}
          - {label: "SEO Description", name: "seo_description", widget: "string"}
          - {label: "SEO Image", name: "seo_image", widget: "image"}

  - name: 'tags' # Used in routes, e.g., /admin/collections/blog
    label: 'Tags' # Used in the UI
    folder: 'src/tags/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
        
  - name: "colors"
    label: "Colors"
    folder: "src/colors/posts"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Color', name: 'color', widget: 'color', enableAlpha: true, allowInput: true }
        
  - name: 'products' # Used in routes, e.g., /admin/collections/blog
    label: 'Products' # Used in the UI
    folder: 'src/products/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
        
      - label: 'Featured Image'
        name: 'deatured_image'
        widget: 'object'
        collapsed: false
        fields: 
          - {lable: "Source", name: "source", widget: "image"}
          - {label: "Alt", name: "alt", widget: "string"}

      - { label: 'Description', name: 'description', widget: 'markdown' }
        
      - label: 'Tags'
        name: 'tags'
        widget: 'relation'
        collection: 'tags'
        value_field: 'title'
        search_fields: ['title']
        multiple: true

      - label: 'Color'
        name: 'color'
        widget: 'relation'
        collection: 'colors'
        value_field: 'title'
        search_fields: ['title']
        multiple: false

      - label: 'Images'
        name: 'images'
        widget: 'list'
        fields: 
            - {lable: "Source", name: "source", widget: "image"}
            - {label: "Alt", name: "alt", widget: "string"}

      - label: "SEO"
        name: "seo"
        widget: "object"
        colapsed: false
        fields: 
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
            
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/pages/posts/home.yml"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro", name: "intro", widget: "markdown"}
          - label: 'Featured Image'
            name: 'deatured_image'
            widget: 'object'
            collapsed: false
            fields: 
            - {lable: "Source", name: "source", widget: "image"}
            - {label: "Alt", name: "alt", widget: "string"}
          - label: "Quotes"
            name: "quotes"
            widget: "list"
            fields:
              - {label: "Quote", name: "quote", widget: "string"}
          - label: "SEO"
            name: "seo"
            widget: "object"
            colapsed: false
            fields: 
             - {label: "Title", name: "title", widget: "string"}
             - {label: "Description", name: "description", widget: "string"}
             - {label: "Image", name: "image", widget: "image"}

      - label: "About page"
        name: "about"
        file: "src/pages/posts/about.yml"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro", name: "intro", widget: "markdown"}
          - label: "Parts"
            name: "part"
            widget: "list"
            fields:
              - {label: "Part title", name: "part_title", widget: "string"}
              - {label: "Info", name: "info", widget: "markdown"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Image Alt", name: "image_alt", widget: "string"}
          - label: "Legal info"
            name: "legal_info"
            widget: "list"
            fields:
              - {label: "Legal text", name: "legal_text", widget: "string"}
          - label: "SEO"
            name: "seo"
            widget: "object"
            colapsed: false
            fields: 
             - {label: "Title", name: "title", widget: "string"}
             - {label: "Description", name: "description", widget: "string"}
             - {label: "Image", name: "image", widget: "image"}