backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: 'src/images' # Media files will be stored in the repo under static/uploads
public_folder: '/images' # The src attribute for uploaded media will begin with /uploads

collections:
  - name: 'categories' # Used in routes, e.g., /admin/collections/blog
    label: 'Categories' # Used in the UI
    folder: 'src/categories/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Order', name: 'order', widget: 'number' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - {
          label: 'Description Images',
          name: 'description_images',
          widget: 'list',
          field: { label: 'Image', name: image, widget: image }
        }
      - {
          label: 'Products',
          name: 'products',
          widget: 'relation',
          collection: 'products',
          value_field: 'title',
          search_fields: ['title'],
          multiple: true
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'relation',
          collection: 'tags',
          value_field: 'title',
          search_fields: ['title'],
          multiple: true
        }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Info', name: 'info', widget: 'markdown' }
      - {
          label: 'Info Images',
          name: 'info_images',
          widget: 'list',
          field: { label: 'Image', name: image, widget: image }
        }
  - name: 'tags' # Used in routes, e.g., /admin/collections/blog
    label: 'Tags' # Used in the UI
    folder: 'src/tags/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
  - name: 'products' # Used in routes, e.g., /admin/collections/blog
    label: 'Products' # Used in the UI
    folder: 'src/products/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
